version: '3.8'

networks:
  net_nodejs_smk:
    driver: bridge
    name: net_nodejs_smk
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1

volumes:
  postgresql16:
    name: postgresql16

services:
  postgres:
    image: iuripetrola/postgresql:v16
    container_name: postgresql16
    restart: unless-stopped
    volumes:
      - postgresql16:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net_nodejs_smk

  node-app:
    image: iuripetrola/nodejs-sonho-meu-kids:latest
    container_name: nodejs_smk
    restart: unless-stopped
    volumes:
      - /mnt/smk:/mnt/arquivos
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - net_nodejs_smk