apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql16
  #namespace: test
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: sc-postgresql16
  nfs:
    server: 10.48.82.2
    path: /consultoria/uploads/test

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql16
  #namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-postgresql16
  resources:
    requests:
      storage: 1Ti